# Generated by Django 4.0.3 on 2022-04-07 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_user_account_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
