# Generated by Django 4.0.3 on 2022-04-25 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_movie_score_alter_user_account_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAttributes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('plot', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=4, null=True)),
                ('comedy', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=4, null=True)),
                ('action', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=4, null=True)),
                ('romance', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=4, null=True)),
                ('animation', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=4, null=True)),
                ('sci_fi', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=4, null=True)),
                ('suspense', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=4, null=True)),
                ('thriller', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=4, null=True)),
                ('fear', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=4, null=True)),
                ('documentary', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=4, null=True)),
                ('short', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=4, null=True)),
                ('erotica', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=4, null=True)),
                ('homosexual', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=4, null=True)),
                ('music', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=4, null=True)),
                ('musical', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=4, null=True)),
                ('family', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=4, null=True)),
                ('children', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=4, null=True)),
                ('biography', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=4, null=True)),
                ('history', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=4, null=True)),
                ('war', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=4, null=True)),
                ('crime', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=4, null=True)),
                ('western', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=4, null=True)),
                ('fantasy', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=4, null=True)),
                ('adventure', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=4, null=True)),
                ('disaster', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=4, null=True)),
                ('martial', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=4, null=True)),
                ('costume', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=4, null=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.user')),
            ],
        ),
        migrations.CreateModel(
            name='MovieAttributes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('plot', models.IntegerField(blank=True, default=0, null=True)),
                ('comedy', models.IntegerField(blank=True, default=0, null=True)),
                ('action', models.IntegerField(blank=True, default=0, null=True)),
                ('romance', models.IntegerField(blank=True, default=0, null=True)),
                ('animation', models.IntegerField(blank=True, default=0, null=True)),
                ('sci_fi', models.IntegerField(blank=True, default=0, null=True)),
                ('suspense', models.IntegerField(blank=True, default=0, null=True)),
                ('thriller', models.IntegerField(blank=True, default=0, null=True)),
                ('fear', models.IntegerField(blank=True, default=0, null=True)),
                ('documentary', models.IntegerField(blank=True, default=0, null=True)),
                ('short', models.IntegerField(blank=True, default=0, null=True)),
                ('erotica', models.IntegerField(blank=True, default=0, null=True)),
                ('homosexual', models.IntegerField(blank=True, default=0, null=True)),
                ('music', models.IntegerField(blank=True, default=0, null=True)),
                ('musical', models.IntegerField(blank=True, default=0, null=True)),
                ('family', models.IntegerField(blank=True, default=0, null=True)),
                ('children', models.IntegerField(blank=True, default=0, null=True)),
                ('biography', models.IntegerField(blank=True, default=0, null=True)),
                ('history', models.IntegerField(blank=True, default=0, null=True)),
                ('war', models.IntegerField(blank=True, default=0, null=True)),
                ('crime', models.IntegerField(blank=True, default=0, null=True)),
                ('western', models.IntegerField(blank=True, default=0, null=True)),
                ('fantasy', models.IntegerField(blank=True, default=0, null=True)),
                ('adventure', models.IntegerField(blank=True, default=0, null=True)),
                ('disaster', models.IntegerField(blank=True, default=0, null=True)),
                ('martial', models.IntegerField(blank=True, default=0, null=True)),
                ('costume', models.IntegerField(blank=True, default=0, null=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.movie')),
            ],
        ),
    ]
