# Generated by Django 4.0.3 on 2022-04-25 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_userattributes_movieattributes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movieattributes',
            name='update_time',
        ),
        migrations.RemoveField(
            model_name='userattributes',
            name='update_time',
        ),
    ]
