# Generated by Django 4.0.3 on 2022-04-26 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_remove_movieattributes_update_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieattributes',
            name='sum_types',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
